name: Artem Saveliev
theme: jekyll-theme-minimal
repository: asaveliev/blog
gems:
  - jekyll-feed
url: https://asaveliev.github.io/blog/
google_analytics: UA-3993903-1
exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
