name: Artem Saveliev
theme: jekyll-theme-minimal
repository: asaveliev/blog
gems:
  - jekyll-feed
url: https://artem.savelev.com/
permalink: /:year/:month/:title/
google_analytics: UA-3993903-1
disqus: asaveliev
exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
title: Artem Saveliev blog
plugins:
  - jekyll-sitemap
